version: 2.1

# CircleCI doesn't handle large file sets properly for local builds
# https://github.com/CircleCI-Public/circleci-cli/issues/281#issuecomment-472808051
localCheckout: &localCheckout
  run: |-
    PROJECT_PATH=$(cd ${CIRCLE_WORKING_DIRECTORY}; pwd)
    mkdir -p ${PROJECT_PATH}
    git config --global --add safe.directory /tmp/_circleci_local_build_repo
    cd /tmp/_circleci_local_build_repo
    git ls-files -z | xargs -0 -s 2090860 tar -c | tar -x -C ${PROJECT_PATH}
    cp -a /tmp/_circleci_local_build_repo/.git ${PROJECT_PATH}

jobs:
  linux_oqs:
    description: A template for running liboqs tests on Linux Docker VMs
    docker:
      - image: openquantumsafe/ci-ubuntu-bionic-i386:latest
    steps:
      - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
      - run:
          name: Configure
          command: mkdir build && cd build && source ~/.bashrc && cmake -GNinja ..
      - run:
          name: Build
          command: ninja
          working_directory: build
      - run:
          name: Run tests
          no_output_timeout: 1h
          command: ./tests/test_sig_stfl XMSS-SHA2_10_256
          working_directory: build

workflows:
  version: 2.1
  build:
    jobs:
      - linux_oqs:
          name: ubuntu-bionic-i386
